[package]
name = "hebbot"
version = "0.1.0"
authors = ["Felix Häcker <haeckerfelix@gnome.org>"]
edition = "2018"
include = ["src/**/*", "Cargo.toml"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
matrix-sdk = "0.3"
matrix-sdk-common = "0.3"
serde = "1.0"
serde_json = "1.0"
url = "2.2"
ruma = "0.2"
tokio = { version="1.7", features = ["macros"] }
async-trait = "0.1"
log = "0.4"
pretty_env_logger = "0.4"
chrono = "0.4"
regex = "1.5"
rand = "0.8"
mime = "0.3"
