services:
  hebbot:
    image: haeckerfelix/hebbot:latest
    restart: unless-stopped
    volumes:
      - hebbot_data:/data
    environment:
      - BOT_PASSWORD=secretpassword
      - CONFIG_PATH=/data/config.toml
      - REPORT_TEMPLATE_PATH=/data/report_template.md
      - SECTION_TEMPLATE_PATH=/data/section_template.md
      - PROJECT_TEMPLATE_PATH=/data/project_template.md
      - STORE_PATH=/data/store.json

volumes:
  hebbot_data:
